# config  for partition project

ens_name: 73

project_catalog:
    project:
        title: partition_cat
        description: partition_cat

extract:
    search_data_catalogs:
        variables_and_freqs:
            tas: D
            tasmax: D
            tasmin: D
            pr: D
        allow_conversion: True
        match_hist_and_fut: True
        periods:
            - 1956
            - 2100
#        exclusions:
#            id:
#             - NEX-GDDP-CMIP6_CMIP6_ScenarioMIP_KIOST_KIOST-ESM_ssp245_r1i1p1f1_QC # time is broken
        restrict_members:
            ordered: 1
        other_search_criteria:
            processing_level:
                - biasadjusted
            source:
                - ACCESS-ESM1-5
                - CanESM5
                - EC-Earth3
                - FGOALS-g3
                - IPSL-CM6A-LR
                - KACE-1-0-G
                - MIROC6
                - MRI-ESM2-0
            bias_adjust_project:
                - CanDCS-U6 # cheat because we want to use the zarr version in other cat.
                - CanDCS-M6
                - ESPO-G6-R2
                - ESPO-G6-E5L
                - ESPO-G6-PB
                - ESPO-G6-EM
                - IC6-R2
                - IC6-E5L
                - IC6-EM
                - IC6-PB
                - IC6-N2014
                #- NEX-GDDP-CMIP6
                - MBCn-E5L
                - MBCn-R2
                - BCCAQv2-E5L
                - BCCAQv2-R2
    extract_dataset:
#        region: # can't pass it directly bc of PCIC R2 lacking lat and lon
#            name: QC
#            method: bbox
#            lon_bnds: [ -83, -55 ]
#            lat_bnds: [ 42, 63 ]
        xr_combine_kwargs:
            combine_attrs: override
        xr_open_kwargs:
            drop_variables:
                - height
                - bnds
                - time_bnds
                - lat_bnds
                - lon_bnds

region:
    name: QC
    method: bbox
    lon_bnds: [ -83, -55 ]
    lat_bnds: [ 42, 63 ]

regrid:
    regrid_dataset:
        regridder_kwargs:
            method: conservative_normed #bilinear used for regrid QC-reg1
            unmapped_to_nan: True
            output_chunks:
                lat: 50
                lon: 50
                time: -1

gridpoints:
    mtl:
        name: mtl
        method: gridpoint
        lat: [45.5]
        lon: [-73.6]
    gas:
        name: gas
        method: gridpoint
        lat: [48.8]
        lon: [-64.5]
    chi:
        name: chi
        method: gridpoint
        lat: [48.4]
        lon: [-71.1]


ensemble:
    84:
        source:
            - ACCESS-ESM1-5
            - CanESM5
            - EC-Earth3
            - FGOALS-g3
            - IPSL-CM6A-LR
            - KACE-1-0-G
            - MIROC6
            - MRI-ESM2-0
        reference:
            - CaSRv2.1
            - ERA5-Land
            - PCICBlend
            - NRCANmet
        method:
            - ESPO-G6
            - IC6
            - MBCn
            - BCCAQv2
        experiment:
            - ssp126
            - ssp245
            - ssp370
            - ssp585
    73:
        source: # no CanESM5
            - ACCESS-ESM1-5
            - EC-Earth3
            - FGOALS-g3
            - IPSL-CM6A-LR
            - KACE-1-0-G
            - MIROC6
            - MRI-ESM2-0
        reference: # no NRCANmet
            - CaSRv2.1
            - ERA5-Land
            - PCICBlend
        method:
            - ESPO-G6
            - IC6
            - MBCn
            - BCCAQv2
        experiment:
            - ssp126
            - ssp245
            - ssp370
            - ssp585

translate:
    method:
        ESPO-G6: ESPO-G6
        IC6: IC6
        CanDCS-U6: BCCAQv2
        CanDCS-M6: MBCn
        NEX: NEX-GDDP
        MBCn: MBCn
        BCCAQv2: BCCAQv2
    reference:
        R2: CaSRv2.1
        E5L: ERA5-Land
        EM: EMDNA
        CanDCS-M6: PCICBlend
        PB: PCICBlend
        CanDCS-U6: NRCANmet
        N2014: NRCANmet
        NEX: GMFD

io:
    save_to_zarr:
        mode: o

tdd:
  xarray_open_kwargs:
    decode_timedelta: False

scripting:
    subject: Partition
    send_mail_on_exit:
        msg_ok: Toutes les étapes demandées ont été complétées.
        msg_err: Une erreur est survenue durant le traitement.
        #on_error_only: True