# config  for partition project

ens_name: 11444

project_catalog:
    project:
        title: partition_cat
        description: partition_cat

extract:
    search_data_catalogs:
        variables_and_freqs:
            tas: D
            tasmax: D
            tasmin: D
            pr: D
        allow_conversion: True
        match_hist_and_fut: True
        periods:
            - 1956
            - 2100
        coverage_kwargs:
            coverage: 0 # skip test for reference
        restrict_members:
            ordered: 1
        other_search_criteria:
            processing_level:
                - biasadjusted
                - extracted
            source:
                - ACCESS-ESM1-5
                - CanESM5
                - EC-Earth3
                - FGOALS-g3
                - IPSL-CM6A-LR
                - KACE-1-0-G
                - MIROC6
                - MRI-ESM2-0
                - CNRM-CM6-1
                - NorESM2-MM
                - UKESM1-0-LL
                # refs
                - PCICBlend
                - ERA5-Land
                - EMDNA
                - RDRS
            bias_adjust_project:
                 - CanDCS-U6
                 - CanDCS-M6
                 - ESPO-G6-R2
                 - ESPO-G6-E5L
                 - ESPO-G6-PB
                 - ESPO-G6-EM
                 - IC6-R2
                 - IC6-E5L
                 - IC6-EM
                 - IC6-PB
                 - MBCn-E5L
                 - MBCn-R2
                 - MBCn-EM
                 - MBCn-PB
                 - BCCAQv2-E5L
                 - BCCAQv2-R2
                 - reference
    extract_dataset:
#        region: # can't pass it directly bc of PCIC R2 lacking lat and lon
#            name: QC
#            method: bbox
#            lon_bnds: [ -83, -55 ]
#            lat_bnds: [ 42, 63 ]
        xr_combine_kwargs:
            combine_attrs: override
        xr_open_kwargs:
            drop_variables:
                - height
                - bnds
                - time_bnds
                - lat_bnds
                - lon_bnds

region:
    name: QC
    method: bbox
    lon_bnds: [ -83, -55 ]
    lat_bnds: [ 42, 63 ]

regrid:
    regrid_dataset:
        regridder_kwargs:
            method: conservative_normed #bilinear used for regrid QC-reg1
            unmapped_to_nan: True
            output_chunks:
                lat: 50
                lon: 50
                time: -1

gridpoints:
    mtl:
        name: mtl
        method: gridpoint
        lat: [45.5]
        lon: [-73.6]
#    sag:
#        name: sag
#        method: gridpoint
#        lat: [ 48.4 ]
#        lon: [ -71.1 ]
    gas:
        name: gas
        method: gridpoint
        lat: [48.8]
        lon: [-64.5]
#    kuu:
#        name: kuu
#        method: gridpoint
#        lat: [ 58.1 ]
#        lon: [ -68.4 ]
#    pin:
#        name: pin
#        method: gridpoint
#        lat: [ 61.4 ]
#        lon: [ -73.7 ]
#    sit:
#        name: sit
#        method: gridpoint
#        lat: [ 58.8 ]
#        lon: [ -75.0 ]
    kaw:
        name: kaw
        method: gridpoint
        lat: [ 54.9 ]
        lon: [ -66.8 ]



ensemble:
    11444: # 592 datasets
        source:
            - ACCESS-ESM1-5
            - CanESM5
            - EC-Earth3
            - FGOALS-g3
            - IPSL-CM6A-LR
            - KACE-1-0-G
            - MIROC6
            - MRI-ESM2-0
            - CNRM-CM6-1
            - NorESM2-MM
            - UKESM1-0-LL
        reference:
            - CaSRv2.1
            - ERA5-Land
            - PCICBlend
            - EMDNA
        adjustment:
            - ESPO-G6
            - IC6
            - MBCn
            - BCCAQv2
        experiment:
            - ssp126
            - ssp245
            - ssp370
            - ssp585
    11443: #444 datasets
        source:
            - ACCESS-ESM1-5
            - CanESM5
            - EC-Earth3
            - FGOALS-g3
            - IPSL-CM6A-LR
            - KACE-1-0-G
            - MIROC6
            - MRI-ESM2-0
            - CNRM-CM6-1
            - NorESM2-MM
            - UKESM1-0-LL
        reference:
            - CaSRv2.1
            - ERA5-Land
            - PCICBlend
            - EMDNA
        adjustment:
            - ESPO-G6
            - IC6
            - MBCn
            - BCCAQv2
        experiment:
            - ssp245
            - ssp370
            - ssp585
    8444:
        source:
            - ACCESS-ESM1-5
            - CanESM5
            - EC-Earth3
            - FGOALS-g3
            - IPSL-CM6A-LR
            - KACE-1-0-G
            - MIROC6
            - MRI-ESM2-0
        reference:
            - CaSRv2.1
            - ERA5-Land
            - PCICBlend
            - EMDNA
        adjustment:
            - ESPO-G6
            - IC6
            - MBCn
            - BCCAQv2
        experiment:
            - ssp126
            - ssp245
            - ssp370
            - ssp585
    7442:
        source: # no CanESM5
            - ACCESS-ESM1-5
            - EC-Earth3
            - FGOALS-g3
            - IPSL-CM6A-LR
            - KACE-1-0-G
            - MIROC6
            - MRI-ESM2-0
        reference: # no NRCANmet
            - CaSRv2.1
            - ERA5-Land
            - PCICBlend
            - EMDNA
        adjustment:
            - ESPO-G6
            - IC6
            - MBCn
            - BCCAQv2
        experiment:
            - ssp245
            - ssp370
    7443: #294 datasets
        source: # no CanESM5
            - ACCESS-ESM1-5
            - EC-Earth3
            - FGOALS-g3
            - IPSL-CM6A-LR
            - KACE-1-0-G
            - MIROC6
            - MRI-ESM2-0
        reference: # no NRCANmet
            - CaSRv2.1
            - ERA5-Land
            - PCICBlend
            - EMDNA
        adjustment:
            - ESPO-G6
            - IC6
            - MBCn
            - BCCAQv2
        experiment:
            - ssp245
            - ssp370
            - ssp585
    7432:
        source: # no CanESM5
            - ACCESS-ESM1-5
            - EC-Earth3
            - FGOALS-g3
            - IPSL-CM6A-LR
            - KACE-1-0-G
            - MIROC6
            - MRI-ESM2-0
        reference: # no NRCANmet
            - CaSRv2.1
            - ERA5-Land
            - PCICBlend
            - EMDNA
        adjustment:
            - ESPO-G6
            - MBCn
            - BCCAQv2
        experiment:
            - ssp245
            - ssp370

# note that in  the paper ESPO-G6 was called DQM and IC6 was called DQM-EV
translate:
    adjustment:
        ESPO-G6: ESPO-G6
        IC6: IC6
        CanDCS-U6: BCCAQv2
        CanDCS-M6: MBCn
        NEX: NEX-GDDP
        MBCn: MBCn
        BCCAQv2: BCCAQv2
    reference:
        R2: CaSRv2.1
        E5L: ERA5-Land
        EM: EMDNA
        CanDCS-M6: PCICBlend
        PB: PCICBlend
        CanDCS-U6: NRCANmet
        N2014: NRCANmet
        NEX: GMFD

io:
    save_to_zarr:
        mode: o

tdd:
  xarray_open_kwargs:
    decode_timedelta: False

scripting:
    send_mail_on_exit:
        msg_ok: Toutes les étapes demandées ont été complétées.
        msg_err: Une erreur est survenue durant le traitement.
        #on_error_only: True